# Creating Website

If you'd like to create your own version of the website, here are the steps you need to follow.

## Prerequisites (half of the battle):

-   Have [R](https://posit.co/download/rstudio-desktop/) and [R studio](https://posit.co/download/rstudio-desktop/) on your local machine

-   Have [Quarto](https://quarto.org/docs/get-started/) on your local machine

- Install the [font awesome extension](https://github.com/quarto-ext/fontawesome) to your computer. You can do this within the terminal in R studio once you've cloned the repository (step 2)

-   Have a [GitHub account](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account)

-   Generate a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) in GitHub. Remember to put the token somewhere safe! You won't be able to look at it again once you exit that window.



## Step-by-step Instructions

1.  [Fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) the [repository](https://github.com/BiodiversityDataScienceCorp/ADS_Cannonical_Version). This should create a repository in your profile at https:://github.com/your-username/ADS_Cannonical_Version.

2.  [Clone](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository) the repository to your local machine. 

3. Integrate GitHub and your credentials into R. You can do this by filling out the [githubConnect.R](githubConnect.R) file in your copy of the repo with your credentials, and running it. Very important: Add the [githubConnect.R](githubConnect.R) file to the [.gitignore](.gitignore) before moving on so you don't accidentally commit your token. Learn more about .gitignore files [here](https://www.freecodecamp.org/news/gitignore-what-is-it-and-how-to-add-to-repo/)

4. Modify! 
Some files that may be especially of interest to modify are the [syllabus](../Info/syllabus.qmd), [schedule](../schedule.qmd), [assignment submission instructions](../Assignments/assignments.qmd), and the [instructor information and contact details](../Info/our_team.qmd). 

