project:
  type: website

website:
  sidebar:
    style: "docked"
    collapse-level: 1
    logo: _images/bdsc-logo-circle.png
    search: true
    contents:
      - section: "Home"
        contents:
        - href: home.qmd
        - href: getting_started.qmd
      - section: "Syllabus"
        contents:
          - href: about.qmd 
      - section: "Schedule"
        contents:
          - href: schedule.qmd
          - href: reading_schedule.qmd 
      - section: "Coding Boot Camp"
        contents: 
          - href: coding_basics_for_this_course.qmd
          - href: Bootcamp/bootcamp_1.qmd
          - href: Bootcamp/bootcamp_2.qmd
          - href: Bootcamp/bootcamp_3.qmd
          - href: Bootcamp/bootcamp_practice_1.qmd
      - section: "Lessons"
        contents:
        - href: data_aquisition_cleaning.qmd
        - href: occ_map.qmd
        - href: sdm_current.qmd
      - section: "Assignment"
        contents:
        - href: Assignments/HW_1.qmd
        - href: Assignments/HW_2_pt1.qmd
        - href: Assignments/HW_2_pt2.qmd
        - href: Assignments/HW_3.qmd
        - href: Assignments/HW_4.qmd
        - href: Assignments/HW_5.qmd
        - href: Assignments/HW_6.qmd
      - section: "People"
        contents:
        - href: about_us.qmd
      
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: source

