project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "General Information"
        contents:
          - about.qmd 
          - index.qmd
      - section: "Course Details"
        contents:
          - for_students.qmd
      - section: "Lessons"
        contents:
        - coding_basics_for_this_course.qmd
        - data_aquisition_cleaning.qmd
        - occ_map.qmd
        - sdm_current.qmd
        - sdm_future_qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

