project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    collapse-level: 1
    logo: _images/bdsc-logo-circle.png
    search: true
    contents:
      - href: home.qmd
      - href: Info/our_team.qmd
      - href: Info/contact_us.qmd
      - href: Info/syllabus.qmd
      - href: schedule.qmd
      - section: "Coding Boot Camp"
        contents: 
          - href: Bootcamp/coding_basics_for_this_course.qmd
          - href: Bootcamp/bootcamp_1.qmd
          - href: Bootcamp/bootcamp_2.qmd
          - href: Bootcamp/bootcamp_3.qmd
          - href: Bootcamp/bootcamp_practice_1.qmd
      - section: "Lessons"
        contents:
        - href: Lessons/lessons.qmd
        - href: Lessons/data_aquisition_cleaning.qmd
        - href: Lessons/occ_map.qmd
        - href: Lesssons/sdm.qmd
      - section: "Assignments"
        contents:
        - href: Assignments/assignments.qmd
        - href: Assignments/HW_1.qmd
        - href: Assignments/HW_2_pt1.qmd
        - href: Assignments/HW_2_pt2.qmd
        - href: Assignments/HW_3.qmd
        - href: Assignments/HW_4.qmd
        - href: Assignments/HW_5.qmd
        - href: Assignments/HW_6.qmd
      - section: "Readings"
        contents:
        - href: Readings/readings.qmd
        - href: Readings/reading_1.qmd
        - href: Readings/reading_2.qmd
        - href: Readings/reading_3.qmd
        - href: Readings/reading_4.qmd
        - href: Readings/reading_5.qmd
      - section: "For Instructors"
        contents:
        - href: For_Instructors/create_website.qmd
        - href: For_Instructors/tips.qmd
      
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: source

