project:
  type: website

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - for_students.qmd
      - about.qmd 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

