---
title: "For Students"
---

## Class Schedule Spring 2023

+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| **Week** | **Date** | **Topics during class time**                                                                                                                                                                                       | **Assignments due**                                                                  | **Important Notes**                                                                                    |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 1        | Jan 10   | Classes start UAZ, no class this week                                                                                                                                                                              | NA                                                                                   | UAZ starts on Wed                                                                                      |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 2        | Jan 17   | Introductions, surveys, creating github account, and preparing for stakeholder meeting                                                                                                                             | In class surveys, In class GitHub registration                                       | First day of class for both schools, grant evaluation survey, getting to know you survey               |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 3        | Jan 24   | Endangered species act lecture, meet USFWS collaborators, and stakeholder interviews                                                                                                                               | HW 1 - Data science tools homework                                                   | Preclass reading on USFWS and ESA; Stakeholder visit with time for informational interviews. HW 1 due. |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 4        | Jan 31   | Group assignments, R studio, github, and project management                                                                                                                                                        | HW 2 - One page resume, summary from informational interviews, Personal course goals | Assign teams, Preclass reading on consulting/project management basics. HW 2 due.                      |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 5        | Feb 7    | Data acquisition, cleaning, and visualization using GBIF                                                                                                                                                           | HW 3 - GitHub Repo with ReadMe for each group                                        | Preclass reading on coding good enough practices and project management in github. HW 3 due.           |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 6        | Feb 14   | Project group work. Focus species data acquisition, cleaning, and mapping                                                                                                                                          | HW 4 - Occurrence map                                                                | Preclass reading on occurrence data wrangling. HW 4 due.                                               |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 7        | Feb 21   | Species distribution models (SDMs)                                                                                                                                                                                 | HW 5 - Natural history/taxonomy summary                                              | Preclass reading on SDMs. HW 5 due.                                                                    |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 8        | Feb 28   | Future SDM in class lesson. Time to discuss deliverables and work flow as a team (time to start updating repos). In class work time for your focal species current and future SDM.                                 | HW 6 - SDMs                                                                          | HW 6 due Friday at midnight.                                                                           |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 9        | Mar 7    | LC meets only. Focus species project group work on organizing GH repo and materials for sharing with stakeholders.                                                                                                 | \                                                                                    | UA Spring Break                                                                                        |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 10       | Mar 14   | Project group work on presentation and GH repo to share with stakeholders.                                                                                                                                         | \                                                                                    | Preclass reading on giving and receiving feedback                                                      |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 11       | Mar 21   | Review group progress. Give a short presentation in class on your species. Each stakeholder will be assigned to 1-2 groups and evaluate deliverables (e.g. taxonomy review, occurrence maps, SDMs) and GitHub Repo | Presentation to stakeholders (GH repo and info on your sp)                           | 2nd USFWS stakeholder visit                                                                            |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 12       | Mar 28   | UA meets only, Project group work re stakeholder feedback                                                                                                                                                          | \                                                                                    | LC Spring Break                                                                                        |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 13       | Apr 4    | Group work re stakeholder feedback                                                                                                                                                                                 | \                                                                                    | \                                                                                                      |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 14       | Apr 11   | Group work for final presentations                                                                                                                                                                                 | \                                                                                    | \                                                                                                      |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 15       | Apr 18   | Stakeholder visit: showcasing student deliverables. Listen and evaluate student presentation and GitHub Repo                                                                                                       | Final presentation to stakeholders                                                   | Final stakeholder visit                                                                                |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 16       | Apr 25   | Submit final project. Reflection and evaluation.                                                                                                                                                                   | Final project submission on github, in-class reflection and survey                   | Last day of class for both institutions, recap and survey in class. Good luck with finals!             |
+----------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+

## Reading Schedule

+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| **Read by class on** | **Links**                                                                                                                                                       | **Reading Questions** |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Jan 24               | [What is a Species Status Assessment (SSA)?](https://www.fws.gov/project/species-status-assessment)                                                             |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [The Endangered Species Act (ESA)](https://www.fws.gov/law/endangered-species-act)                                                                              |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [Ecological Services provided by the US Fish and Wildlife Service](https://www.fws.gov/program/ecological-services)                                             |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [What US Fish and Wildlife Service does with the ESA](https://www.fws.gov/program/endangered-species)                                                           |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Jan 31               | [R (programming language)](https://en.wikipedia.org/wiki/R_(programming_language))                                                                              |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [IDE](https://en.wikipedia.org/wiki/Integrated_development_environment)                                                                                         |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [The Center for Open Science](https://www.cos.io/)                                                                                                              |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [UNESCO Recommendations for Open Science](https://www.youtube.com/watch?v=I3Wkvx_ZaFo)                                                                          |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Feb 7                | [Data cleaning](https://www.tableau.com/learn/articles/what-is-data-cleaning)                                                                                   |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [iNaturalist and Scientific Discoveries](https://edis.ifas.ufl.edu/publication/UW458) - read through Data Validation                                            |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [Uses of GBIF in conservation](https://www.gbif.org/conservation)  - watch the video                                                                            |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Feb 14               | [Scientific article on public database accuracy for SDMs](https://onlinelibrary.wiley.com/doi/10.1111/geb.12326) - case study, read introduction and discussion |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [Abstract from Biodiversity Information Science and Standards 2022](https://biss.pensoft.net/article/93823/) - conference proceedings abstract                  |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [USGS Wildlife wrangler GitLab](https://code.usgs.gov/sas/bioscience/wildlife-wrangler) - read ReadMe.md especially Valuable Features                           |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Feb 21               | [Ecological niche](https://www.youtube.com/watch?v=z31y-ZtegZ8&feature=youtu.be)                                                                                |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [General intro to the concept of SDM](https://www.natureserve.org/products/species-distribution-modeling)                                                       |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [More detailed slide deck about SDM](https://docs.google.com/presentation/d/1h7zgDBwZowA9LJMD-Oj-LH3YrkgaK1vA/edit#slide=id.p1)                                 |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [About MaxEnt, a type of SDM](https://support.bccvl.org.au/support/solutions/articles/6000083216-maxent)                                                        |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Feb 28               | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| March 7              | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| March 14             | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| March 21             | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| March 28             | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| April 4              | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| April 11             | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| April 18             | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
