## Reading Schedule

+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| **Read by class on** | **Links**                                                                                                                                                       | **Reading Questions** |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Jan 24               | [What is a Species Status Assessment (SSA)?](https://www.fws.gov/project/species-status-assessment)                                                             |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [The Endangered Species Act (ESA)](https://www.fws.gov/law/endangered-species-act)                                                                              |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [Ecological Services provided by the US Fish and Wildlife Service](https://www.fws.gov/program/ecological-services)                                             |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [What US Fish and Wildlife Service does with the ESA](https://www.fws.gov/program/endangered-species)                                                           |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Jan 31               | [R (programming language)](https://en.wikipedia.org/wiki/R_(programming_language))                                                                              |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [IDE](https://en.wikipedia.org/wiki/Integrated_development_environment)                                                                                         |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [The Center for Open Science](https://www.cos.io/)                                                                                                              |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [UNESCO Recommendations for Open Science](https://www.youtube.com/watch?v=I3Wkvx_ZaFo)                                                                          |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Feb 7                | [Data cleaning](https://www.tableau.com/learn/articles/what-is-data-cleaning)                                                                                   |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [iNaturalist and Scientific Discoveries](https://edis.ifas.ufl.edu/publication/UW458) - read through Data Validation                                            |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [Uses of GBIF in conservation](https://www.gbif.org/conservation)  - watch the video                                                                            |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Feb 14               | [Scientific article on public database accuracy for SDMs](https://onlinelibrary.wiley.com/doi/10.1111/geb.12326) - case study, read introduction and discussion |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [Abstract from Biodiversity Information Science and Standards 2022](https://biss.pensoft.net/article/93823/) - conference proceedings abstract                  |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [USGS Wildlife wrangler GitLab](https://code.usgs.gov/sas/bioscience/wildlife-wrangler) - read ReadMe.md especially Valuable Features                           |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Feb 21               | [Ecological niche](https://www.youtube.com/watch?v=z31y-ZtegZ8&feature=youtu.be)                                                                                |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [General intro to the concept of SDM](https://www.natureserve.org/products/species-distribution-modeling)                                                       |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [More detailed slide deck about SDM](https://docs.google.com/presentation/d/1h7zgDBwZowA9LJMD-Oj-LH3YrkgaK1vA/edit#slide=id.p1)                                 |                       |
|                      |                                                                                                                                                                 |                       |
|                      | [About MaxEnt, a type of SDM](https://support.bccvl.org.au/support/solutions/articles/6000083216-maxent)                                                        |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Feb 28               | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| March 7              | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| March 14             | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| March 21             | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| March 28             | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| April 4              | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| April 11             | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| April 18             | \                                                                                                                                                               |                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
