---
title: "Class Schedule"
---

## Class Schedule

| **Week** | **Topic**                           | **Reading**                                    | **Lesson**                                                           | **Assignment**                                  |
|----------|-------------------------------------|------------------------------------------------|----------------------------------------------------------------------|-------------------------------------------------|
| 1        | Accounts creation                   | [{{< fa book-open >}}](Readings/reading_1.qmd) |                                                                      | [{{< fa keyboard >}}](Assignments/HW_1.qmd)     |
| 2        | Endangered Species Act              | [{{< fa book-open >}}](Readings/reading_2.qmd) |                                                                      | [{{< fa keyboard >}}](Assignments/HW_2_pt1.qmd) |
| 3        | GitHub, R, R studio                 | [{{< fa book-open >}}](Readings/reading_3.qmd) | [{{< fa person-chalkboard >}}](Lessons/github_rstudio.qmd)           | [{{< fa keyboard >}}](Assignments/HW_3.qmd)     |
| 4        | GBIF - data wrangling, viz          | [{{< fa book-open >}}](Readings/reading_4.qmd) | [{{< fa person-chalkboard >}}](Lessons/data_aquisition_cleaning.qmd) | [{{< fa keyboard >}}](Assignments/HW_4.qmd)     |
| 5        | Focal species - data wrangling, viz | [{{< fa book-open >}}](Readings/reading_5.qmd) |                                                                      | [{{< fa keyboard >}}](Assignments/HW_5.qmd)     |
| 6        | Current SDM                         |                                                | [{{< fa person-chalkboard >}}](Lessons/sdm.qmd)                      |                                                 |
| 7        | Future SDM                          |                                                | [{{< fa person-chalkboard >}}](Lessons/sdm.qmd)                      | [{{< fa keyboard >}}](Assignments/HW_6.qmd)     |
| 8        | Focal species SDM                   |                                                |                                                                      |                                                 |
| 9        | Focal species presentation + repo   |                                                |                                                                      |                                                 |
| 10       | Presentation                        |                                                |                                                                      |                                                 |
| 11       | Group work re stakeholder feedback  |                                                |                                                                      |                                                 |
| 12       | Group work re stakeholder feedback  |                                                |                                                                      |                                                 |
| 13       | Group work for final presentations  |                                                |                                                                      |                                                 |
| 14       | Stakeholder visit                   |                                                |                                                                      |                                                 |
| 15       | Reflection and evaluation           |                                                |                                                                      |                                                 |
